In [3]:
import numpy as np

In [4]:
def get_L1(act_for_L1):
    return np.linalg.norm(act_for_L1.T,1,axis = 1) / act_for_L1.shape[1]

In [64]:
n,d = 5,10

In [95]:
a = np.zeros((n,d))
a[0] += 5
a[1] += 2
a[:,4] += 6
a[:,7] += 2
a[4,1] = 10

In [96]:
a

array([[ 5.,  5.,  5.,  5., 11.,  5.,  5.,  7.,  5.,  5.],
       [ 2.,  2.,  2.,  2.,  8.,  2.,  2.,  4.,  2.,  2.],
       [ 0.,  0.,  0.,  0.,  6.,  0.,  0.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  6.,  0.,  0.,  2.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  6.,  0.,  0.,  2.,  0.,  0.]])

In [103]:
a.mean(axis=0)

array([1.4, 3.4, 1.4, 1.4, 7.4, 1.4, 1.4, 3.4, 1.4, 1.4])

In [104]:
np.linalg.norm(a,2,axis = 0) / a.shape[0]

array([1.07703296, 2.27156334, 1.07703296, 1.07703296, 3.42344855,
       1.07703296, 1.07703296, 1.75499288, 1.07703296, 1.07703296])

In [101]:
np.median(a[:,1])

2.0

In [102]:
np.median(a,axis=0)

array([0., 2., 0., 0., 6., 0., 0., 2., 0., 0.])

In [75]:
np.linalg.norm(a.T,1,axis = 1) / a.shape[1]

array([1. , 1.9, 1. , 1. , 6. , 1. , 1. , 2. , 1. , 1. ])

In [76]:
a.shape[1]

10